config/routes.rb
Rails.application.routes.draw do  
  get 'estado_medidors/index_ruta' => 'estado_medidors#index_ruta', as: :index_ruta
  resources :estado_medidors
  resources :ruta_users
  resources :ruta
  resources :empleados
  resources :users
  resources :roles
  resources :usuario_medidors
  resources :usuarios
  resources :medidors
  resources :usuarios
  devise_for :users, :path => 'user'
  resources :personas
  resources :tipo_medidors
  resources :novedads
  resources :prioridads
  resources :tipo_documentos
  resources :categoria
  resources :zonas
  resources :grupos
  get 'index/index'

  root 'index#index'

  get 'index' => 'index#index'
  get 'personas/find_persona/:tipo_documento_id/:nro_documento' => 'personas#find_persona', as: :find_persona
  get 'usuarios/get_medidores/:usuario_id' => 'usuarios#get_medidores', as: :get_medidores

  post 'restful/signin' => 'restful#signin', as: :signin
  post 'restful/signup' => 'restful#signup', as: :signup
  post 'restful/descargar_ruta' => 'restful#descargar_ruta', as: :descargar_ruta
  post 'restful/guardar_medicion' => 'restful#guardar_medicion', as: :guardar_medicion

  get 'restful/chequear_ruta' => 'restful#chequear_ruta', as: :chequear_ruta 
  

end

app/models/novedad.rb
class Novedad < ApplicationRecord
  belongs_to :prioridad

  validates :codigo, presence: { message: "Debe completar el campo Código" }
  validates :codigo, length: {minimum: 1, maximum: 2, message: "El campo Código debe tener 2 dígitos"}
  validates :descripcion, presence: { message: "Debe completar el campo Descripción" }
  validates :codigo_servicio, presence: { message: "Debe completar el campo Código de servicio" }

  def to_s 
  	"#{self.codigo} - #{self.descripcion}"	
  end
end

app/controllers/novedads_controller.rb
class NovedadsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_novedad, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /novedads
  # GET /novedads.json
  def index
    @novedads = Novedad.all
  end

  # GET /novedads/1
  # GET /novedads/1.json
  def show
  end

  # GET /novedads/new
  def new
    @novedad = Novedad.new
  end

  # GET /novedads/1/edit
  def edit
  end

  # POST /novedads
  # POST /novedads.json
  def create
    @novedad = Novedad.new(novedad_params)

    respond_to do |format|
      if @novedad.save
        format.html { redirect_to @novedad, notice: 'Se ha creado una nueva Novedad.' }
        format.json { render :show, status: :created, location: @novedad }
      else
        format.html { render :new }
        format.json { render json: @novedad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /novedads/1
  # PATCH/PUT /novedads/1.json
  def update
    respond_to do |format|
      if @novedad.update(novedad_params)
        format.html { redirect_to @novedad, notice: 'Se ha actualizado la Novedad.' }
        format.json { render :show, status: :ok, location: @novedad }
      else
        format.html { render :edit }
        format.json { render json: @novedad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /novedads/1
  # DELETE /novedads/1.json
  def destroy
    @novedad.destroy
    respond_to do |format|
      format.html { redirect_to novedads_url, notice: 'Se ha eliminado la Novedad.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_novedad
      @novedad = Novedad.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def novedad_params
      params.require(:novedad).permit(:codigo, :descripcion, :prioridad_id, :codigo_servicio, :repite_estado)
    end
end

app/helpers/novedads_helper.rb
module NovedadsHelper
end

app/views/novedads/_form.html.erb
<%= form_for(@novedad, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @novedad.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Cerrar</span></button>
      <h5><b><%= fa_icon "exclamation-circle", text: "Atención! Ocurrieron los siguientes errores" %></b></h5>
      <ul>
      <% @novedad.errors.messages.values.each do |msg| %>
        <%msg.each do  |m| %>
          <li><%= m %></li>
        <%end %>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :codigo, "Código", class: "col-sm-2 control-label" %>
    <div class="col-sm-2">
      <%= f.number_field :codigo, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :descripcion, "Descripción", class: "col-sm-2 control-label" %>
    <div class="col-sm-6">
      <%= f.text_field :descripcion, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :prioridad_id, "Prioridad", class: "col-sm-2 control-label" %>
    <div class="col-sm-5">
      <%= f.collection_select :prioridad_id, Prioridad.all, :id, :to_s, {prompt: false}, {:class => "form-control"} %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :codigo_servicio, "Código de servicio", class: "col-sm-2 control-label" %>
    <div class="col-sm-2">
      <%= f.text_field :codigo_servicio, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :repite_estado, class: "col-sm-2 control-label" %>
    <div class="col-sm-2">
      <%= f.check_box :repite_estado, { class: 'form-control' }, "true", "false" %>      
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary", value: "Guardar"%>
    </div>
  </div>
<% end %>

app/views/novedads/edit.html.erb
<div class="page-header">
  <%= link_to novedads_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Volver
  <% end %>
  <%= link_to @novedad, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Ver
  <% end %>
  <h4>Editar Novedad</h4>
</div>
<ol class="breadcrumb">
  <li>
    <%= link_to novedads_path do %>
        <%= fa_icon "newspaper-o", text: "Novedades" %>
    <% end %>
  </li>
  <li class="active">
    Editar Novedad
  </li>
</ol>

<%= render 'form' %>

app/views/novedads/index.html.erb
<div class="page-header">
  <%= link_to new_novedad_path, class: 'btn btn-primary' do %>
    <%= fa_icon "plus", text: "Nueva Novedad" %>
  <% end %>
  <h4>Listado de Novedades</h4>
</div>
<ol class="breadcrumb">
  <li class="active">
    <%= fa_icon "newspaper-o", text: "Novedades" %>
  </li>
</ol>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Código</th>
            <th>Descripción</th>
            <th>Prioridad</th>
            <th>Código de servicio</th>
            <th>Repite estado</th>
            <th class="col-md-2">&nbsp;</th>
      </tr>
    </thead>

    <tbody>
      <% @novedads.each do |novedad| %>
        <tr>
          <td><%= novedad.codigo %></td>
          <td><%= novedad.descripcion %></td>
          <td><%= novedad.prioridad %></td>
          <td><%= novedad.codigo_servicio %></td>
          <td><%= (novedad.repite_estado)? "SI": "NO" %></td>
          <td class="text-center">
          <%= link_to novedad, class: 'btn btn-sm btn-default' do %>
            <span class="glyphicon glyphicon-search"></span>
          <% end %>
          <%= link_to edit_novedad_path(novedad), class: 'btn btn-sm btn-default' do %>
            <span class="glyphicon glyphicon-pencil"></span>
          <% end %>
          <%= link_to novedad, class: 'btn btn-sm btn-danger',method: :delete, data: { confirm: '¿Está seguro?' } do %>
            <span class="glyphicon glyphicon-trash"></span>
          <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/novedads/new.html.erb
<div class="page-header">
  <%= link_to novedads_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Volver
  <% end %>
  <h4>Nueva Novedad</h4>
</div>
<ol class="breadcrumb">
  <li>
    <%= link_to novedads_path do %>
        <%= fa_icon "newspaper-o", text: "Novedades" %>
    <% end %>
  </li>
  <li class="active">
    Nueva Novedad
  </li>
</ol>

<%= render 'form' %>

app/views/novedads/show.html.erb
<div class="page-header">
  <%= link_to novedads_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Volver
  <% end %>
  <%= link_to edit_novedad_path(@novedad), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Editar
  <% end %>
  <h4>Ver Novedad</h4>
</div>
<ol class="breadcrumb">
  <li>
    <%= link_to novedads_path do %>
        <%= fa_icon "newspaper-o", text: "Novedades" %>
    <% end %>
  </li>
  <li class="active">
    Nueva Novedad
  </li>
</ol>

<dl class="dl-horizontal">
  <dt>Código:</dt>
  <dd><%= @novedad.codigo %></dd>

  <dt>Descripción:</dt>
  <dd><%= @novedad.descripcion %></dd>

  <dt>Prioridad:</dt>
  <dd><%= @novedad.prioridad %></dd>

  <dt>Código de servicio:</dt>
  <dd><%= @novedad.codigo_servicio %></dd>

  <dt>Repite estado:</dt>
  <dd><%= (@novedad.repite_estado)? "SI": "NO" %></dd>

</dl>