config/routes.rb
Rails.application.routes.draw do  
  get 'estado_medidors/index_ruta' => 'estado_medidors#index_ruta', as: :index_ruta
  resources :estado_medidors
  resources :ruta_users
  resources :ruta
  resources :empleados
  resources :users
  resources :roles
  resources :usuario_medidors
  resources :usuarios
  resources :medidors
  resources :usuarios
  devise_for :users, :path => 'user'
  resources :personas
  resources :tipo_medidors
  resources :novedads
  resources :prioridads
  resources :tipo_documentos
  resources :categoria
  resources :zonas
  resources :grupos
  get 'index/index'

  root 'index#index'

  get 'index' => 'index#index'
  get 'personas/find_persona/:tipo_documento_id/:nro_documento' => 'personas#find_persona', as: :find_persona
  get 'usuarios/get_medidores/:usuario_id' => 'usuarios#get_medidores', as: :get_medidores

  post 'restful/signin' => 'restful#signin', as: :signin
  post 'restful/signup' => 'restful#signup', as: :signup
  post 'restful/descargar_ruta' => 'restful#descargar_ruta', as: :descargar_ruta
  post 'restful/guardar_medicion' => 'restful#guardar_medicion', as: :guardar_medicion

  get 'restful/chequear_ruta' => 'restful#chequear_ruta', as: :chequear_ruta 
  

end

app/models/medidor.rb
class Medidor < ApplicationRecord
  belongs_to :tipo_medidor

  has_many :usuario_medidors, :foreign_key => 'medidor_id', :class_name => 'UsuarioMedidor'
  has_many :usuarios, :through => :usuario_medidors

  has_many :medidor_estado_medidors, :foreign_key => 'medidor_id', :class_name => 'MedidorEstadoMedidor'
  has_many :estado_medidors, :through => :medidor_estado_medidors

  validates :numero, :presence => { :message => "Debe completar el campo Número" }
  validates :numero, length: {minimum: 1, maximum: 8, :message => "El campo Número puede tener hasta 8 dígitos"}
  validates :multiplicador, :presence => { :message => "Debe completar el campo Multiplicador" }
  validates :multiplicador, length: {minimum: 1, maximum: 3, :message => "El campo Multiplicador puede tener hasta 3 dígitos"}
  validates :marca, :presence => { :message => "Debe completar el campo Marca" }
  validates :modelo, :presence => { :message => "Debe completar el campo Modelo" }

  def to_s
	 "Medidor N°: #{self.numero} - #{self.marca} - #{self.modelo}, (#{self.tipo_medidor})"
  end
end

app/controllers/medidors_controller.rb
class MedidorsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_medidor, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /medidors
  # GET /medidors.json
  def index
    @medidors = Medidor.all
  end

  # GET /medidors/1
  # GET /medidors/1.json
  def show
  end

  # GET /medidors/new
  def new
    @medidor = Medidor.new
  end

  # GET /medidors/1/edit
  def edit
  end

  # POST /medidors
  # POST /medidors.json
  def create
    @medidor = Medidor.new(medidor_params)
    @medidor.fecha_alta = DateTime.now

    respond_to do |format|
      if @medidor.save
        estado_medidor = EstadoMedidor.create(novedad_id: 1, user_id: current_user.id, estado_actual: 0, estado_anterior: 0, promedio: 0,fecha_medicion: DateTime.now)
        MedidorEstadoMedidor.create(medidor_id: @medidor.id, estado_medidor_id: estado_medidor.id)
        format.html { redirect_to @medidor, notice: 'Se ha creado un nuevo Medidor.' }
        format.json { render :show, status: :created, location: @medidor }
      else
        format.html { render :new }
        format.json { render json: @medidor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /medidors/1
  # PATCH/PUT /medidors/1.json
  def update
    respond_to do |format|
      if @medidor.update(medidor_params)
        format.html { redirect_to @medidor, notice: 'Se ha actualizado el Medidor.' }
        format.json { render :show, status: :ok, location: @medidor }
      else
        format.html { render :edit }
        format.json { render json: @medidor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medidors/1
  # DELETE /medidors/1.json
  def destroy    
    estado_ids = @medidor.medidor_estado_medidors.map(&:estado_medidor_id)
    @medidor.medidor_estado_medidors.destroy_all
    EstadoMedidor.where(id: estado_ids).destroy_all
    @medidor.destroy
    respond_to do |format|
      format.html { redirect_to medidors_url, notice: 'Se ha eliminado el Medidor.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_medidor
      @medidor = Medidor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def medidor_params
      params.require(:medidor).permit(:numero, :multiplicador, :marca, :modelo, :fecha_alta, :fecha_baja, :tipo_medidor_id)
    end
end

app/helpers/medidors_helper.rb
module MedidorsHelper
end

app/views/medidors/_form.html.erb
<%= form_for(@medidor, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @medidor.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Cerrar</span></button>
      <h5><b><%= fa_icon "exclamation-circle", text: "Atención! Ocurrieron los siguientes errores" %></b></h5>
      <ul>
      <% @medidor.errors.messages.values.each do |msg| %>
        <%msg.each do  |m| %>
          <li><%= m %></li>
        <%end %>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :numero, "Número", class: "col-sm-3 control-label" %>
    <div class="col-sm-2">
      <%= f.number_field :numero, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :multiplicador, class: "col-sm-3 control-label" %>
    <div class="col-sm-4">
      <%= f.number_field :multiplicador, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :marca, class: "col-sm-3 control-label" %>
    <div class="col-sm-5">
      <%= f.text_field :marca, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :modelo, class: "col-sm-3 control-label" %>
    <div class="col-sm-5">
      <%= f.text_field :modelo, class: "form-control" %>
    </div>
  </div>  
  <div class="form-group">
    <%= f.label :tipo_medidor_id, "Tipo de medidor", class: "col-sm-3 control-label" %>
    <div class="col-sm-4">
      <%= f.collection_select :tipo_medidor_id, TipoMedidor.all, :id, :to_s, {prompt: false}, {:class => "form-control"} %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary", value: "Guardar"%>
    </div>
  </div>
<% end %>

app/views/medidors/edit.html.erb
<div class="page-header">
  <%= link_to medidors_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Volver
  <% end %>
  <%= link_to @medidor, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Ver
  <% end %>
  <h4>Editar Medidor</h4>
</div>
<ol class="breadcrumb">
  <li>
    <%= link_to medidors_path do %>
        <%= fa_icon "calculator", text: "Medidores" %>
    <% end %>
  </li>
  <li class="active">
    Editar Medidor
  </li>
</ol>

<%= render 'form' %>

app/views/medidors/index.html.erb
<div class="page-header">
  <%= link_to new_medidor_path, class: 'btn btn-primary' do %>
    <%= fa_icon "plus", text: "Nuevo Medidor" %>
  <% end %>
  <h4>Listado de Medidores</h4>
</div>
<ol class="breadcrumb">
  <li class="active">
    <%= fa_icon "calculator", text: "Medidores" %>
  </li>
</ol>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Número</th>
            <th>Multiplicador</th>
            <th>Marca</th>
            <th>Modelo</th>
            <!-- <th>Fecha alta</th>
            <th>Fecha baja</th> -->
            <th>Tipo medidor</th>
            <th class="col-md-2">&nbsp;</th>
      </tr>
    </thead>

    <tbody>
      <% @medidors.each do |medidor| %>
        <tr>
          <td><%= medidor.numero %></td>
          <td><%= medidor.multiplicador %></td>
          <td><%= medidor.marca %></td>
          <td><%= medidor.modelo %></td>
          <!-- <td><%= medidor.fecha_alta %></td>
          <td><%= medidor.fecha_baja %></td> -->
          <td><%= medidor.tipo_medidor %></td>
          <td class="text-center">
            <%= link_to medidor, class: 'btn btn-sm btn-default' do %>
              <span class="glyphicon glyphicon-search"></span>
            <% end %>
            <%= link_to edit_medidor_path(medidor), class: 'btn btn-sm btn-default' do %>
              <span class="glyphicon glyphicon-pencil"></span>
            <% end %>
            <%= link_to medidor, class: 'btn btn-sm btn-danger',method: :delete, data: { confirm: '¿Está seguro?' } do %>
              <span class="glyphicon glyphicon-trash"></span>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/medidors/new.html.erb
<div class="page-header">
  <%= link_to medidors_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Volver
  <% end %>
  <h4>Nuevo Medidor</h4>
</div>
<ol class="breadcrumb">
  <li>
    <%= link_to medidors_path do %>
        <%= fa_icon "calculator", text: "Medidores" %>
    <% end %>
  </li>
  <li class="active">
    Nuevo Medidor
  </li>
</ol>

<%= render 'form' %>

app/views/medidors/show.html.erb
<div class="page-header">
  <%= link_to medidors_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Volver
  <% end %>
  <%= link_to edit_medidor_path(@medidor), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Editar
  <% end %>
  <h4>Ver Medidor</h4>
</div>
<ol class="breadcrumb">
  <li>
    <%= link_to medidors_path do %>
        <%= fa_icon "calculator", text: "Medidores" %>
    <% end %>
  </li>
  <li class="active">
    Ver Medidor
  </li>
</ol>

<dl class="dl-horizontal">
  <dt>Número:</dt>
  <dd><%= @medidor.numero %></dd>

  <dt>Multiplicador:</dt>
  <dd><%= @medidor.multiplicador %></dd>

  <dt>Marca:</dt>
  <dd><%= @medidor.marca %></dd>

  <dt>Modelo:</dt>
  <dd><%= @medidor.modelo %></dd>

  <dt>Fecha de alta:</dt>
  <dd><%= @medidor.fecha_alta %></dd>

  <dt>Fecha de baja:</dt>
  <dd><%= @medidor.fecha_baja %></dd>

  <dt>Tipo de medidor:</dt>
  <dd><%= @medidor.tipo_medidor %></dd>

</dl>