config/routes.rb
Rails.application.routes.draw do  
  get 'estado_medidors/index_ruta' => 'estado_medidors#index_ruta', as: :index_ruta
  resources :estado_medidors
  resources :ruta_users
  resources :ruta
  resources :empleados
  resources :users
  resources :roles
  resources :usuario_medidors
  resources :usuarios
  resources :medidors
  resources :usuarios
  devise_for :users, :path => 'user'
  resources :personas
  resources :tipo_medidors
  resources :novedads
  resources :prioridads
  resources :tipo_documentos
  resources :categoria
  resources :zonas
  resources :grupos
  get 'index/index'

  root 'index#index'

  get 'index' => 'index#index'
  get 'personas/find_persona/:tipo_documento_id/:nro_documento' => 'personas#find_persona', as: :find_persona
  get 'usuarios/get_medidores/:usuario_id' => 'usuarios#get_medidores', as: :get_medidores

  post 'restful/signin' => 'restful#signin', as: :signin
  post 'restful/signup' => 'restful#signup', as: :signup
  post 'restful/descargar_ruta' => 'restful#descargar_ruta', as: :descargar_ruta
  post 'restful/guardar_medicion' => 'restful#guardar_medicion', as: :guardar_medicion

  get 'restful/chequear_ruta' => 'restful#chequear_ruta', as: :chequear_ruta 
  

end

app/models/tipo_medidor.rb
class TipoMedidor < ApplicationRecord
	validates :nombre, :presence => { :message => "Debe completar el campo Nombre" }
	validates :codigo, :presence => { :message => "Debe completar el campo Código" }
  	validates :codigo, numericality: { only_integer: true, :message => "El campo Código debe ser un valor entero"}
  	validates :descripcion, :presence => { :message => "Debe completar el campo Descripción" }

	def to_s
		self.nombre
	end
end

app/controllers/tipo_medidors_controller.rb
class TipoMedidorsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_tipo_medidor, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /tipo_medidors
  # GET /tipo_medidors.json
  def index
    @tipo_medidors = TipoMedidor.all
  end

  # GET /tipo_medidors/1
  # GET /tipo_medidors/1.json
  def show
  end

  # GET /tipo_medidors/new
  def new
    @tipo_medidor = TipoMedidor.new
  end

  # GET /tipo_medidors/1/edit
  def edit
  end

  # POST /tipo_medidors
  # POST /tipo_medidors.json
  def create
    @tipo_medidor = TipoMedidor.new(tipo_medidor_params)

    respond_to do |format|
      if @tipo_medidor.save
        format.html { redirect_to @tipo_medidor, notice: 'Se ha creado un nuevo Tipo de Medidor.' }
        format.json { render :show, status: :created, location: @tipo_medidor }
      else
        format.html { render :new }
        format.json { render json: @tipo_medidor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tipo_medidors/1
  # PATCH/PUT /tipo_medidors/1.json
  def update
    respond_to do |format|
      if @tipo_medidor.update(tipo_medidor_params)
        format.html { redirect_to @tipo_medidor, notice: 'Se ha actualizado el Tipo de Medidor.' }
        format.json { render :show, status: :ok, location: @tipo_medidor }
      else
        format.html { render :edit }
        format.json { render json: @tipo_medidor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipo_medidors/1
  # DELETE /tipo_medidors/1.json
  def destroy
    @tipo_medidor.destroy
    respond_to do |format|
      format.html { redirect_to tipo_medidors_url, notice: 'Se ha eliminado el Tipo de Medidor.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tipo_medidor
      @tipo_medidor = TipoMedidor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tipo_medidor_params
      params.require(:tipo_medidor).permit(:nombre, :codigo, :descripcion)
    end
end

app/helpers/tipo_medidors_helper.rb
module TipoMedidorsHelper
end

app/views/tipo_medidors/_form.html.erb
<%= form_for(@tipo_medidor, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @tipo_medidor.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Cerrar</span></button>
      <h5><b><%= fa_icon "exclamation-circle", text: "Atención! Ocurrieron los siguientes errores" %></b></h5>
      <ul>
      <% @tipo_medidor.errors.messages.values.each do |msg| %>
        <%msg.each do  |m| %>
          <li><%= m %></li>
        <%end %>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nombre, class: "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.text_field :nombre, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :codigo, "Código", class: "col-sm-2 control-label" %>
    <div class="col-sm-2">
      <%= f.number_field :codigo, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :descripcion, "Descripción", class: "col-sm-2 control-label" %>
    <div class="col-sm-5">
      <%= f.text_field :descripcion, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary", value: "Guardar"%>
    </div>
  </div>
<% end %>

app/views/tipo_medidors/edit.html.erb
<div class="page-header">
  <%= link_to tipo_medidors_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Volver
  <% end %>
  <%= link_to @tipo_medidor, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Ver
  <% end %>
  <h4>Editar Tipo de medidor</h4>
</div>
<ol class="breadcrumb">
  <li>
    <%= link_to tipo_medidors_path do %>
        <%= fa_icon "calculator", text: "Tipos de medidores" %>
    <% end %>
  </li>
  <li class="active">
    Editar Tipo de medidor
  </li>
</ol>

<%= render 'form' %>

app/views/tipo_medidors/index.html.erb
<div class="page-header">
  <%= link_to new_tipo_medidor_path, class: 'btn btn-primary' do %>
    <%= fa_icon "plus", text: "Nuevo Tipo de medidor" %>
  <% end %>
  <h4>Listado de Tipo de medidores</h4>
</div>
<ol class="breadcrumb">
  <li class="active">
    <%= fa_icon "calculator", text: "Tipos de medidores" %>
  </li>
</ol>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Nombre</th>
            <th>Código</th>
            <th>Descripción</th>
            <th class="col-md-2">&nbsp;</th>
      </tr>
    </thead>

    <tbody>
      <% @tipo_medidors.each do |tipo_medidor| %>
        <tr>
          <td><%= tipo_medidor.nombre %></td>
          <td><%= tipo_medidor.codigo %></td>
          <td><%= tipo_medidor.descripcion %></td>
          <td class="text-center">
            <%= link_to tipo_medidor, class: 'btn btn-sm btn-default' do %>
              <span class="glyphicon glyphicon-search"></span>
            <% end %>
            <%= link_to edit_tipo_medidor_path(tipo_medidor), class: 'btn btn-sm btn-default' do %>
              <span class="glyphicon glyphicon-pencil"></span>
            <% end %>
            <%= link_to tipo_medidor, class: 'btn btn-sm btn-danger',method: :delete, data: { confirm: '¿Está seguro?' } do %>
              <span class="glyphicon glyphicon-trash"></span>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/tipo_medidors/new.html.erb
<div class="page-header">
  <%= link_to tipo_medidors_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Volver
  <% end %>
  <h4>Nuevo Tipo de medidor</h4>
</div>
<ol class="breadcrumb">
  <li>
    <%= link_to tipo_medidors_path do %>
        <%= fa_icon "calculator", text: "Tipos de medidores" %>
    <% end %>
  </li>
  <li class="active">
    Nuevo Tipo de medidor
  </li>
</ol>

<%= render 'form' %>

app/views/tipo_medidors/show.html.erb
<div class="page-header">
  <%= link_to tipo_medidors_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Volver
  <% end %>
  <%= link_to edit_tipo_medidor_path(@tipo_medidor), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Editar
  <% end %>
  <h4>Ver Tipo de medidor</h4>
</div>
<ol class="breadcrumb">
  <li>
    <%= link_to tipo_medidors_path do %>
        <%= fa_icon "calculator", text: "Tipos de medidores" %>
    <% end %>
  </li>
  <li class="active">
    Ver Tipo de medidor
  </li>
</ol>

<dl class="dl-horizontal">
  <dt>Nombre:</dt>
  <dd><%= @tipo_medidor.nombre %></dd>

  <dt>Código:</dt>
  <dd><%= @tipo_medidor.codigo %></dd>

  <dt>Descripción:</dt>
  <dd><%= @tipo_medidor.descripcion %></dd>

</dl>