config/routes.rb
Rails.application.routes.draw do  
  get 'estado_medidors/index_ruta' => 'estado_medidors#index_ruta', as: :index_ruta
  resources :estado_medidors
  resources :ruta_users
  resources :ruta
  resources :empleados
  resources :users
  resources :roles
  resources :usuario_medidors
  resources :usuarios
  resources :medidors
  resources :usuarios
  devise_for :users, :path => 'user'
  resources :personas
  resources :tipo_medidors
  resources :novedads
  resources :prioridads
  resources :tipo_documentos
  resources :categoria
  resources :zonas
  resources :grupos
  get 'index/index'

  root 'index#index'

  get 'index' => 'index#index'
  get 'personas/find_persona/:tipo_documento_id/:nro_documento' => 'personas#find_persona', as: :find_persona
  get 'usuarios/get_medidores/:usuario_id' => 'usuarios#get_medidores', as: :get_medidores

  post 'restful/signin' => 'restful#signin', as: :signin
  post 'restful/signup' => 'restful#signup', as: :signup
  post 'restful/descargar_ruta' => 'restful#descargar_ruta', as: :descargar_ruta
  post 'restful/guardar_medicion' => 'restful#guardar_medicion', as: :guardar_medicion

  get 'restful/chequear_ruta' => 'restful#chequear_ruta', as: :chequear_ruta 
  

end

app/models/empleado.rb
class Empleado < ApplicationRecord
  belongs_to :tipo_documento

  validates :nro_documento, :presence => { :message => "Debe completar el campo Número de documento" }
  validates :nro_documento, numericality: { only_integer: true, :message => "El campo Número de documento debe ser un valor entero"}
  validates :nro_documento, length: {minimum: 7, maximum: 11, :message => "El campo Número de documento debe tener 7 u 11 dígitos"}
  validates :apellido, :presence => { :message => "Debe completar el campo Apellido" }
  validates :apellido, :format => {:with => /\A[a-z ñáéíóúü'A-ZÑÁÉÍÓÚÜ]+\z/, :message => "El campo Apellido sólo debe contener letras" }
  validates :nombre, :presence => { :message => "Debe completar el campo Nombre" }
  validates :nombre, :format => {:with => /\A[a-z ñáéíóúü'A-ZÑÁÉÍÓÚÜ]+\z/, :message => "El campo Nombre sólo debe contener letras" }  

  def to_s
  	"#{self.nro_documento} - #{self.apellido}, #{self.nombre}"  	
  end
end

app/controllers/empleados_controller.rb
class EmpleadosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_empleado, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /empleados
  # GET /empleados.json
  def index
    @empleados = Empleado.all
  end

  # GET /empleados/1
  # GET /empleados/1.json
  def show
  end

  # GET /empleados/new
  def new
    @empleado = Empleado.new
  end

  # GET /empleados/1/edit
  def edit
  end

  # POST /empleados
  # POST /empleados.json
  def create
    @empleado = Empleado.new(empleado_params)

    respond_to do |format|
      if @empleado.save
        format.html { redirect_to @empleado, notice: 'Se ha creado un nuevo empleado.' }
        format.json { render :show, status: :created, location: @empleado }
      else
        format.html { render :new }
        format.json { render json: @empleado.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /empleados/1
  # PATCH/PUT /empleados/1.json
  def update
    respond_to do |format|
      if @empleado.update(empleado_params)
        format.html { redirect_to @empleado, notice: 'Se ha actualizado el empleado.' }
        format.json { render :show, status: :ok, location: @empleado }
      else
        format.html { render :edit }
        format.json { render json: @empleado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /empleados/1
  # DELETE /empleados/1.json
  def destroy
    @empleado.destroy
    respond_to do |format|
      format.html { redirect_to empleados_url, notice: 'Se ha eliminado el empleado.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_empleado
      @empleado = Empleado.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def empleado_params
      params.require(:empleado).permit(:nro_legajo, :tipo_documento_id, :nro_documento, :apellido, :nombre, :fecha_alta, :fecha_baja)
    end
end

app/helpers/empleados_helper.rb
module EmpleadosHelper
end

app/views/empleados/_form.html.erb
<%= form_for(@empleado, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @empleado.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Cerrar</span></button>
      <h5><b><%= fa_icon "exclamation-circle", text: "Atención! Ocurrieron los siguientes errores" %></b></h5>
      <ul>
      <% @empleado.errors.messages.values.each do |msg| %>
        <%msg.each do  |m| %>
          <li><%= m %></li>
        <%end %>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nro_legajo, "N° de legajo", class: "col-sm-2 control-label" %>
    <div class="col-sm-2">
      <%= f.number_field :nro_legajo, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :tipo_documento_id, "Tipo de documento", class: "col-sm-2 control-label" %>
    <div class="col-sm-2">
      <%= f.collection_select :tipo_documento_id, TipoDocumento.all, :id, :to_s, {prompt: false}, {:class => "form-control"} %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :nro_documento, "N° de documento", class: "col-sm-2 control-label" %>
    <div class="col-sm-2">
      <%= f.number_field :nro_documento, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :apellido, class: "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.text_field :apellido, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :nombre, class: "col-sm-2 control-label" %>
    <div class="col-sm-5">
      <%= f.text_field :nombre, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary", value: "Guardar"%>
    </div>
  </div>
<% end %>

app/views/empleados/edit.html.erb
<div class="page-header">
  <%= link_to empleados_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Volver
  <% end %>
  <%= link_to @empleado, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Ver
  <% end %>
  <h4>Editar Empleado</h4>
</div>
<ol class="breadcrumb">
  <li>
    <%= link_to personas_path do %>
        <%= fa_icon "male", text: "Empleados" %>
    <% end %>
  </li>
  <li class="active">
    Editar Empleado
  </li>
</ol>

<%= render 'form' %>

app/views/empleados/index.html.erb
<div class="page-header">
  <%= link_to new_empleado_path, class: 'btn btn-primary' do %>
    <%= fa_icon "plus", text: "Nuevo Empleado" %>
  <% end %>
  <h4>Listado de Empleados</h4>
</div>
<ol class="breadcrumb">
  <li class="active">
    <%= fa_icon "male", text: "Empleados" %>
  </li>
</ol>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>N° de legajo</th>
            <th>Tipo de documento</th>
            <th>N° de documento</th>
            <th>Apellido</th>
            <th>Nombre</th>
            <th class="text-center">Estado</th>
            <th class="col-md-2">&nbsp;</th>
      </tr>
    </thead>

    <tbody>
      <% @empleados.each do |empleado| %>
        <tr>
          <td><%= empleado.nro_legajo %></td>
          <td><%= empleado.tipo_documento %></td>
          <td><%= empleado.nro_documento %></td>
          <td><%= empleado.apellido %></td>
          <td><%= empleado.nombre %></td>
          <td class="text-center">
            <span class="label label-<%= empleado.fecha_baja != nil ? 'danger' : 'success' %>">
              <%= empleado.fecha_baja != nil ? "Baja" : "Alta" %>
            </span>
          </td>
          <td class="text-center">
          <%= link_to empleado, class: 'btn btn-sm btn-default' do %>
            <span class="glyphicon glyphicon-search"></span>
          <% end %>
          <%= link_to edit_empleado_path(empleado), class: 'btn btn-sm btn-default' do %>
            <span class="glyphicon glyphicon-pencil"></span>
          <% end %>
          <%= link_to empleado, class: 'btn btn-sm btn-danger',method: :delete, data: { confirm: '¿Está seguro?' } do %>
            <span class="glyphicon glyphicon-trash"></span>
          <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/empleados/new.html.erb
<div class="page-header">
  <%= link_to empleados_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Volver
  <% end %>
  <h4>Nuevo Empleado</h4>
</div>
<ol class="breadcrumb">
  <li>
    <%= link_to personas_path do %>
        <%= fa_icon "male", text: "Empleados" %>
    <% end %>
  </li>
  <li class="active">
    Nuevo Empleado
  </li>
</ol>

<%= render 'form' %>

app/views/empleados/show.html.erb
<div class="page-header">
  <%= link_to empleados_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Volver
  <% end %>
  <%= link_to edit_empleado_path(@empleado), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Editar
  <% end %>
  <h4>Ver Empleado</h4>
</div>
<ol class="breadcrumb">
  <li>
    <%= link_to personas_path do %>
        <%= fa_icon "male", text: "Empleados" %>
    <% end %>
  </li>
  <li class="active">
    Ver Empleado
  </li>
</ol>

<dl class="dl-horizontal">
  <dt>N° de legajo:</dt>
  <dd><%= @empleado.nro_legajo %></dd>

  <dt>Tipo de documento:</dt>
  <dd><%= @empleado.tipo_documento %></dd>

  <dt>N° documento:</dt>
  <dd><%= @empleado.nro_documento %></dd>

  <dt>Apellido:</dt>
  <dd><%= @empleado.apellido %></dd>

  <dt>Nombre:</dt>
  <dd><%= @empleado.nombre %></dd>

  <dt>Fecha de alta:</dt>
  <dd><%= @empleado.fecha_alta %></dd>

  <dt>Fecha de baja:</dt>
  <dd><%= @empleado.fecha_baja %></dd>

</dl>